# -*- coding: utf-8 -*-
"""Class 1 INST 326 Project 2 Jason.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cv_0cNMaabwa0SinTzUYNKeBkbvI3fUc
"""

class Library:
    """
     A library management system for organizing and searching books.

    This class provides functionality to add, search, retrieve, and delete books
    from a library catalog. Books are stored with title, author, year, and ISBN.

    Attributes:
        books (list): A private list of book dictionaries in the library catalog.

    Examples:
        >>> library = Library()
        >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
        >>> library.add_book("Animal Farm", "George Orwell", 1945, "978-0451526342")
        >>> len(library.books)
        2
        >>> results = library.search_books("orwell")
        >>> len(results)
        2
  """

    def __init__(self):
        """
        Initialize a new Library instance with an empty book catalog.

        The books list is stored as a private attribute to encourage
        controlled access through class methods.
        """
        self._books = []

    @property
    def books(self):
        """
        Get a copy of the books list to prevent external modification.

        Returns:
            list: A shallow copy of the books catalog.

        Examples:
            >>> library = Library()
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> books = library.books
            >>> len(books)
            1
        """
        return self._books.copy()

    @property
    def book_count(self):
        """
        Get the total number of books in the library.

        Returns:
            int: The number of books in the catalog.

        Examples:
            >>> library = Library()
            >>> library.book_count
            0
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> library.book_count
            1
        """
        return len(self._books)

    def add_book(self, title, author, year, isbn):
        """
        Add a new book to the library catalog.

        Args:
            title (str): The title of the book. Must be non-empty.
            author (str): The author of the book. Must be non-empty.
            year (int): The publication year. Must be between 1000 and 2100.
            isbn (str): The ISBN of the book. Must be non-empty.

        Raises:
            ValueError: If any parameter fails validation.
            TypeError: If year is not an integer.

        Examples:
            >>> library = Library()
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> library.book_count
            1
            >>> library.add_book("", "Author", 2000, "123")
            Traceback (most recent call last):
                ...
            ValueError: Title must be a non-empty string
        """
        # Parameter validation
        if not isinstance(title, str) or not title.strip():
            raise ValueError("Title must be a non-empty string")

        if not isinstance(author, str) or not author.strip():
            raise ValueError("Author must be a non-empty string")

        if not isinstance(year, int):
            raise TypeError("Year must be an integer")

        if year < 1000 or year > 2100:
            raise ValueError("Year must be between 1000 and 2100")

        if not isinstance(isbn, str) or not isbn.strip():
            raise ValueError("ISBN must be a non-empty string")

        # Check for duplicate ISBN
        if self.get_book(isbn) is not None:
            raise ValueError(f"Book with ISBN {isbn} already exists")

        book = {
            "title": title.strip(),
            "author": author.strip(),
            "year": year,
            "isbn": isbn.strip()
        }
        self._books.append(book)

    def display_books(self):
        """
        Display all books in the library to the console.

        Prints each book's details in dictionary format. If the library
        is empty, prints a message indicating no books are available.

        Examples:
            >>> library = Library()
            >>> library.display_books()
            No books in the library.
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> library.display_books()
            {'title': '1984', 'author': 'George Orwell', 'year': 1949, 'isbn': '978-0451524935'}
        """
        if not self._books:
            print("No books in the library.")
            return

        for book in self._books:
            print(book)

    def search_books(self, query):
        """
        Search for books by title or author (case-insensitive).

        Args:
            query (str): The search term to match against titles and authors.

        Returns:
            list: A list of book dictionaries matching the query.
                  Returns empty list if no matches found.

        Raises:
            ValueError: If query is not a string or is empty.

        Examples:
            >>> library = Library()
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> library.add_book("Animal Farm", "George Orwell", 1945, "978-0451526342")
            >>> results = library.search_books("orwell")
            >>> len(results)
            2
            >>> results = library.search_books("1984")
            >>> results[0]['title']
            '1984'
            >>> library.search_books("nonexistent")
            []
        """
        if not isinstance(query, str) or not query.strip():
            raise ValueError("Query must be a non-empty string")

        query = query.lower().strip()
        results = []

        for book in self._books:
            if query in book["title"].lower() or query in book["author"].lower():
                results.append(book)

        return results

    def get_book(self, isbn):
        """
        Get a specific book by its ISBN.

        Args:
            isbn (str): The ISBN of the book to retrieve.

        Returns:
            dict or None: The book dictionary if found, None otherwise.

        Raises:
            ValueError: If ISBN is not a string or is empty.

        Examples:
            >>> library = Library()
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> book = library.get_book("978-0451524935")
            >>> book['title']
            '1984'
            >>> library.get_book("999-9999999999") is None
            True
        """
        if not isinstance(isbn, str) or not isbn.strip():
            raise ValueError("ISBN must be a non-empty string")

        isbn = isbn.strip()

        for book in self._books:
            if book["isbn"] == isbn:
                return book

        return None

    def delete_book(self, isbn):
        """
        Remove a book from the catalog by ISBN.

        This method is useful for removing books that are lost, damaged,
        or outdated from the library catalog.

        Args:
            isbn (str): The ISBN of the book to delete.

        Returns:
            bool: True if book was found and deleted, False otherwise.

        Raises:
            ValueError: If ISBN is not a string or is empty.

        Examples:
            >>> library = Library()
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> library.delete_book("978-0451524935")
            True
            >>> library.book_count
            0
            >>> library.delete_book("999-9999999999")
            False
        """
        if not isinstance(isbn, str) or not isbn.strip():
            raise ValueError("ISBN must be a non-empty string")

        isbn = isbn.strip()

        for book in self._books:
            if book["isbn"] == isbn:
                self._books.remove(book)
                return True

        return False

    def __str__(self):
        """
        Return a user-friendly string representation of the library.

        Returns:
            str: A formatted string showing the library status.

        Examples:
            >>> library = Library()
            >>> str(library)
            'Library with 0 books'
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> str(library)
            'Library with 1 book'
        """
        count = self.book_count
        book_word = "book" if count == 1 else "books"
        return f"Library with {count} {book_word}"

    def __repr__(self):
        """
        Return a detailed string representation for debugging.

        Returns:
            str: A string that could be used to recreate the object.

        Examples:
            >>> library = Library()
            >>> repr(library)
            'Library(books=0)'
            >>> library.add_book("1984", "George Orwell", 1949, "978-0451524935")
            >>> repr(library)
            'Library(books=1)'
        """
        return f"Library(books={self.book_count})"


# Example usage and demonstrations
if __name__ == "__main__":
    # Create a new library
    library = Library()
    print("Created library:", library)
    print()

    # Add some books
    print("Adding books...")
    library.add_book("1984", "George Orwell", 1949, "978-0451524935")
    library.add_book("To Kill a Mockingbird", "Harper Lee", 1960, "978-0061120084")
    library.add_book("Animal Farm", "George Orwell", 1945, "978-0451526342")
    print(library)
    print()

    # Display all books
    print("All books in library:")
    library.display_books()
    print()

    # Search for books
    print("Search results for 'orwell':")
    results = library.search_books("orwell")
    for book in results:
        print(f"  - {book['title']} ({book['year']})")
    print()

    # Get specific book
    print("Get book by ISBN '978-0451524935':")
    book = library.get_book("978-0451524935")
    if book:
        print(f"  Found: {book['title']} by {book['author']}")
    print()

    # Delete a book
    print("Deleting '1984'...")
    deleted = library.delete_book("978-0451524935")
    print(f"  Deletion successful: {deleted}")
    print(library)
    print()

    # Try to delete non-existent book
    print("Trying to delete non-existent book...")
    deleted = library.delete_book("999-9999999999")
    print(f"  Deletion successful: {deleted}")
    print()

    # Demonstrate validation
    print("Testing parameter validation:")
    try:
        library.add_book("", "Author", 2000, "123")
    except ValueError as e:
        print(f"  Caught error: {e}")

    try:
        library.add_book("Title", "Author", "not a year", "123")
    except TypeError as e:
        print(f"  Caught error: {e}")

    try:
        library.add_book("Title", "Author", 3000, "123")
    except ValueError as e:
        print(f"  Caught error: {e}")