# -*- coding: utf-8 -*-
"""Joseph_Edited.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Jglo34/All-of-the-above/blob/main/Joseph_Edited.ipynb
"""



class Library:
    """Represents a library with book management functions."""

    def calculate_late_fee(self, days_late, fee_per_day=0.25):
        """Calculates the late fee based on days late and fee per day."""
        if days_late < 0:
            return "Invalid input: Days late cannot be negative."
        else:
            return days_late * fee_per_day

    def find_books_by_genre(self, genre, book_list):
        """Finds books in a list that match a given genre."""
        matching_books = [book for book in book_list if book['genre'].lower() == genre.lower()]
        return matching_books

    def find_book_by_isbn(self, isbn, book_list):
        """Finds a book in a list by its ISBN."""
        for book in book_list:
            if book['isbn'] == isbn:
                return book
        return "Book not found with that ISBN."

    def check_out_book(self, book_title, user_name):
        """Simulates checking out a book."""
        return f"{book_title} checked out by {user_name}."

    def return_book(self, book_title, user_name):
        """Simulates returning a book."""
        return f"{book_title} returned by {user_name}."