# -*- coding: utf-8 -*-
"""project2Adeshola.ipynbADELEKE2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IyN42ODca7cBPmiJ7kC9MDoVLYDXbAt
"""

class Library2:
    """
    A library management system with book availability and member checkout tracking.

    This class expands on the basic Library by including book availability,
    genres, and member borrowing history.

    Attributes:
        _books (list): A private list of book dictionaries in the library catalog.
        _checkouts (list): A private list of member checkout records.

    Examples:
        >>> lib = Library2()
        >>> lib.add_book("1984", "George Orwell", 1949, "978-0451524935", "Dystopian")
        >>> lib.add_book("Animal Farm", "George Orwell", 1945, "978-0451526342", "Satire")
        >>> len(lib.books)
        2
        >>> lib.books[0]['available']
        True
    """

    def __init__(self):
        """
        Initialize a new Library2 instance with empty book and checkout lists.
        """
        self._books = []
        self._checkouts = []

    @property
    def books(self):
        """
        Get a copy of all books in the library.

        Returns:
            list: A shallow copy of the books list.

        Examples:
            >>> lib = Library2()
            >>> lib.add_book("1984", "George Orwell", 1949, "978-0451524935", "Dystopian")
            >>> len(lib.books)
            1
        """
        return self._books.copy()

    @property
    def checkouts(self):
        """
        Get a copy of all checkout records.

        Returns:
            list: A shallow copy of the checkout records list.

        Examples:
            >>> lib = Library2()
            >>> lib.checkouts
            []
        """
        return self._checkouts.copy()

    @property
    def book_count(self):
        """
        Get the total number of books in the library.

        Returns:
            int: The total number of books.

        Examples:
            >>> lib = Library2()
            >>> lib.book_count
            0