# -*- coding: utf-8 -*-
"""Both sections of code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrFvDWADdPTrkD2YZKM2462AzpoYZ1GW
"""

import abc
from datetime import date, timedelta
from abc import ABC, abstractmethod

# =================================================================
# 1. ABSTRACT BASE CLASS & INHERITANCE (Requirements 1 & 2)
# =================================================================

class LibraryItem(ABC):
    """
    Abstract Base Class (ABC) for all library items.
    Defines the common interface (check_out, return_item)
    and the abstract method (calculate_loan_period).
    """
    def __init__(self, title: str, isbn: str, year: int, available: bool = True):
        if not all([title, isbn, year]):
            raise ValueError("Title, ISBN, and Year must be provided.")
        self.title = title
        self.isbn = isbn
        self.year = year
        self.available = available

    def __str__(self):
        status = "Available" if self.available else "Checked Out"
        return f"{self.__class__.__name__}: '{self.title}' (ISBN: {self.isbn}) - {status}"

    @abstractmethod
    def calculate_loan_period(self) -> int:
        """
        Abstract method. Must be implemented by subclasses to define
        their specific loan duration in days.
        """
        pass

    def check_out(self):
        """
        Common method for loaning an item, utilizing the polymorphic
        calculate_loan_period() method.
        """
        if not self.available:
            return None, "Item is already checked out."

        loan_days = self.calculate_loan_period() # Polymorphic call
        self.available = False
        due_date = date.today() + timedelta(days=loan_days)
        return due_date, f"'{self.title}' checked out. Due date: {due_date.isoformat()} ({loan_days} days)."

# --- Derived Classes (Specialization using method overriding and super()) ---

class Book(LibraryItem):
    """Derived class for standard Books."""
    def __init__(self, title, isbn, year, author, genre):
        super().__init__(title, isbn, year) # super() call
        self.author = author
        self.genre = genre

    def calculate_loan_period(self) -> int:
        """Loan period for a standard Book is 14 days."""
        return 14

class DVD(LibraryItem):
    """Derived class for DVDs."""
    def __init__(self, title, isbn, year, director):
        super().__init__(title, isbn, year) # super() call
        self.director = director

    def calculate_loan_period(self) -> int:
        """Loan period for a DVD is 3 days."""
        return 3

class EBook(LibraryItem):
    """Derived class for EBooks."""
    def __init__(self, title, isbn, year, author, file_size):
        super().__init__(title, isbn, year) # super() call
        self.author = author
        self.file_size = file_size

    def calculate_loan_period(self) -> int:
        """EBooks have a longer loan period: 28 days."""
        return 28

# =================================================================
# 2. COMPOSITION (Requirement 4)
# =================================================================

class LibraryCatalog:
    """
    The main container class (Composition).
    It 'has-a' collection of LibraryItem objects.
    """
    def __init__(self):
        # Uses Composition: stores instances of LibraryItem
        self._items: dict[str, LibraryItem] = {}

    def add_item(self, item: LibraryItem):
        """Adds any LibraryItem object to the catalog."""
        if item.isbn in self._items:
            raise ValueError(f"Item with ISBN {item.isbn} already exists.")
        self._items[item.isbn] = item
        print(f"Catalog added: {item.title}")

    def get_item(self, isbn) -> LibraryItem | None:
        """Retrieves an item by its ISBN."""
        return self._items.get(isbn)

    @property
    def all_items(self):
        """Returns a list of all items."""
        return list(self._items.values())


class LoanManager:
    """
    Manages checkouts and returns.
    It 'has-a' reference to the LibraryCatalog (Composition).
    """
    def __init__(self, catalog: LibraryCatalog):
        # Uses Composition: stores a reference to a LibraryCatalog object
        self._catalog = catalog
        self._checkouts: dict[str, dict] = {} # {isbn: {"user": name, "due_date": date}}

    # =================================================================
    # 3. POLYMORPHISM DEMONSTRATION (Requirement 3)
    # =================================================================
    def checkout_item(self, user_name: str, isbn: str):
        """
        Checks out an item using polymorphic behavior.
        The system handles different item types uniformly.
        """
        item = self._catalog.get_item(isbn)
        if not item:
            return "Error: Item not found."

        # Polymorphic call: Same method produces different results (loan days)
        due_date, message = item.check_out()

        if due_date:
            self._checkouts[isbn] = {"user": user_name, "due_date": due_date}
            return f"{message} User: {user_name}"
        return message

    def return_item(self, isbn: str, days_late: int = 0, fee_per_day: float = 0.50):
        """Handles return and fee calculation."""
        item = self._catalog.get_item(isbn)
        if not item:
            return "Error: Item not found."
        if item.available:
            return "Item was not checked out."

        item.available = True
        user_name = self._checkouts.pop(isbn, {}).get("user", "Unknown")

        fee = max(days_late * fee_per_day, 0)
        return f"{user_name} returned '{item.title}'. Late fee: ${fee:.2f}"

# =================================================================
# USAGE DEMONSTRATION
# =================================================================

if __name__ == "__main__":
    print("--- 🏛️ LIBRARY SYSTEM INITIALIZATION ---")

    # 1. Initialize Composition classes
    catalog = LibraryCatalog()
    loan_manager = LoanManager(catalog)

    # 2. Instantiate and Add Derived Item Types
    book1 = Book("1984", "9780451524935", 1949, "George Orwell", "Dystopian")
    dvd1 = DVD("2001: A Space Odyssey", "D9999", 1968, "Stanley Kubrick")
    ebook1 = EBook("Python Guide", "E8888", 2023, "G. Programmer", 10.5)

    catalog.add_item(book1)
    catalog.add_item(dvd1)
    catalog.add_item(ebook1)

    print("\n--- 3. POLYMORPHIC CHECKOUT ---")

    # The LoanManager calls the generic 'check_out',
    # but the result (loan period) is specialized by the derived class.

    # Book (14 days loan)
    print(loan_manager.checkout_item("Alice", "9780451524935"))

    # DVD (3 days loan)
    print(loan_manager.checkout_item("Bob", "D9999"))

    # EBook (28 days loan)
    print(loan_manager.checkout_item("Charlie", "E8888"))

    print("\n--- 4. ITEM STATUS ---")
    for item in catalog.all_items:
        print(item)

    print("\n--- 5. RETURN & FEE CALCULATION ---")
    # Return Book 10 days late (Fee: 10 * $0.50 = $5.00)
    print(loan_manager.return_item("9780451524935", days_late=10))

    # Return DVD on time (Fee: $0.00)
    print(loan_manager.return_item("D9999", days_late=0))

    # Attempt to checkout the Book again (should succeed)
    print(loan_manager.checkout_item("Dave", "9780451524935"))