# -*- coding: utf-8 -*-
"""Firstpartofproject03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gSS0oV3pqhbxtsbHMVuk-jVHQcS8V6t
"""

import abc
from datetime import date, timedelta
from abc import ABC, abstractmethod

# =================================================================
# 1. ABSTRACT BASE CLASS & INHERITANCE (Requirements 1 & 2)
# =================================================================

class LibraryItem(ABC):
    """
    Abstract Base Class (ABC) for all library items.
    Defines the common interface (check_out, return_item)
    and the abstract method (calculate_loan_period).
    """
    def __init__(self, title: str, isbn: str, year: int, available: bool = True):
        if not all([title, isbn, year]):
            raise ValueError("Title, ISBN, and Year must be provided.")
        self.title = title
        self.isbn = isbn
        self.year = year
        self.available = available

    def __str__(self):
        status = "Available" if self.available else "Checked Out"
        return f"{self.__class__.__name__}: '{self.title}' (ISBN: {self.isbn}) - {status}"

    @abstractmethod
    def calculate_loan_period(self) -> int:
        """
        Abstract method. Must be implemented by subclasses to define
        their specific loan duration in days.
        """
        pass

    def check_out(self):
        """
        Common method for loaning an item, utilizing the polymorphic
        calculate_loan_period() method.
        """
        if not self.available:
            return None, "Item is already checked out."

        loan_days = self.calculate_loan_period() # Polymorphic call
        self.available = False
        due_date = date.today() + timedelta(days=loan_days)
        return due_date, f"'{self.title}' checked out. Due date: {due_date.isoformat()} ({loan_days} days)."

# --- Derived Classes (Specialization using method overriding and super()) ---

class Book(LibraryItem):
    """Derived class for standard Books."""
    def __init__(self, title, isbn, year, author, genre):
        super().__init__(title, isbn, year) # super() call
        self.author = author
        self.genre = genre

    def calculate_loan_period(self) -> int:
        """Loan period for a standard Book is 14 days."""
        return 14

class DVD(LibraryItem):
    """Derived class for DVDs."""
    def __init__(self, title, isbn, year, director):
        super().__init__(title, isbn, year) # super() call
        self.director = director

    def calculate_loan_period(self) -> int:
        """Loan period for a DVD is 3 days."""
        return 3

class EBook(LibraryItem):
    """Derived class for EBooks."""
    def __init__(self, title, isbn, year, author, file_size):
        super().__init__(title, isbn, year) # super() call
        self.author = author
        self.file_size = file_size

    def calculate_loan_period(self) -> int:
        """EBooks have a longer loan period: 28 days."""
        return 28

# =================================================================
# 2. COMPOSITION (Requirement 4)
# =================================================================

class LibraryCatalog:
    """
    The main container class (Composition).
    It 'has-a' collection of LibraryItem objects.
    """
    def __init__(self):
        # Uses Composition: stores instances of LibraryItem
        self._items: dict[str, LibraryItem] = {}

    def add_item(self, item: LibraryItem):
        """Adds any LibraryItem object to the catalog."""
        if item.isbn in self._items:
            raise ValueError(f"Item with ISBN {item.isbn} already exists.")
        self._items[item.isbn] = item
        print(f"Catalog added: {item.title}")

    def get_item(self, isbn) -> LibraryItem | None:
        """Retrieves an item by its ISBN."""
        return self._items.get(isbn)

    @property
    def all_items(self):
        """Returns a list of all items."""
        return list(self._items.values())


class LoanManager:
    """
    Manages checkouts and returns.
    It 'has-a' reference to the LibraryCatalog (Composition).
    """
    def __init__(self, catalog: LibraryCatalog):
        # Uses Composition: stores a reference to a LibraryCatalog object
        self._catalog = catalog
        self._checkouts: dict[str, dict] = {} # {isbn: {"user": name, "due_date": date}}